<?php
    $title = 'Delete Task';
    $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
    $url = $this->url('task', [
        'action' => 'delete',
        'id' => $id
    ]);
?>

<form action="<?php echo $url; ?>" method="POST">
    <p>Are you sure to delete this task?</p>

    <ul class="list-group">
        <li class="list-group-item align-items-center">
            <span>Title: </span><?php echo $task->getTitle(); ?>
        </li>
        <li class="list-group-item align-items-center">
            <span>Description: </span><?php echo $task->getDescription(); ?>
        </li>
        <li class="list-group-item align-items-center">
            <span>Status: </span><?php echo $task->getStatus(); ?>
        </li>
        <li class="list-group-item align-items-center">
            <span>Created At: </span><?php echo date("d/m/Y H:i:s", strtotime($task->getCreatedAt())); ?>
        </li>
        <?php if ($task->getUpdatedAt()): ?>
            <li class="list-group-item align-items-center">
                <span>Updated At: </span><?php echo date("d/m/Y H:i:s", strtotime($task->getUpdatedAt())); ?>
            </li>
        <?php else: ?>
            <li class="list-group-item align-items-center">
                <span>Updated At: Task not updated</span>
            </li>
        <?php endif;?>
    </ul>

    <div class="form-group">
        <input type="hidden" name="id" value="<?php echo $task->getId(); ?>">
        <input type="submit" name="delete" value="Yes" class="btn btn-danger">
        <input type="submit" name="delete" value="No" class="btn btn-primary">
    </div>
</form>