<?php
    $title = 'View Task Details';
    $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<ul class="list-group">
    <li class="list-group-item align-items-center">
        <span>Title: </span><?php echo $task->getTitle(); ?>
    </li>
    <li class="list-group-item align-items-center">
        <span>Description: </span><?php echo $task->getDescription(); ?>
    </li>
    <li class="list-group-item align-items-center">
        <span>Status: </span><?php echo $task->getStatus(); ?>
    </li>
    <li class="list-group-item align-items-center">
        <span>Created At: </span><?php echo date("d/m/Y H:i:s", strtotime($task->getCreatedAt())); ?>
    </li>
    <?php if ($task->getUpdatedAt()): ?>
        <li class="list-group-item align-items-center">
            <span>Updated At: </span><?php echo date("d/m/Y H:i:s", strtotime($task->getUpdatedAt())); ?>
        </li>
    <?php else: ?>
        <li class="list-group-item align-items-center">
            <span>Updated At: Task not updated</span>
        </li>
    <?php endif;?>
</ul>

<div>
    <a href="<?php echo $this->url('task',['action' => 'index']); ?>" class="btn btn-primary">Back</a>
</div>